### ISSUE TITLE
which sha1.h library do you use?

### ISSUE THREAD

**Issue by peefour** [lucadentella/ArduinoLib_TOTP#1]
hello luca!

thanks for this nice library !!

I have a question though,

you use sha1.h but from which library? 

you mention 3 libraries: 
Jose Damico, https://github.com/damico/ARDUINO-OATH-TOKEN
Peter Knight, https://github.com/Cathedrow/Cryptosuite
Maniacbug, https://github.com/maniacbug/Cryptosuite

which one do you use?

**Comment by lucadentella** [comment]
Hi! Please use the ManiacBug one: it's a fork of the original work by Peter but it has been updated to work with Arduino 1.0 or later.
