### ISSUE TITLE
How to verify a code

### ISSUE THREAD

**Issue by lgaticaq** [lucadentella/ArduinoLib_TOTP#3]
Hello

How to verify a code generate by app (authy or google auth) in arduino?

**Comment by lucadentella** [comment]
Hello! 
1. use the library to generate the corresponding token in Arduino, using the same private key your GAuth uses and the same timestamp (better use an RTC synced with the UTC time)
2. compare the two codes (the one the user reads from the GAuth and the one Arduino generates

Please give a look at the example provided and/or at the OTP Door Lock project linked in the README.

**Comment by lgaticaq** [comment]
thank
