### ISSUE TITLE
Enhance to support HOTP?

### ISSUE THREAD

**Issue by Apollon77** [lucadentella/ArduinoLib_TOTP#4]
Would it be possible to enhance the lib to also support HOTP?

**Comment by lucadentella** [comment]
Hi! HOTP is basically the same as TOTP but the variable value is not something related to the time but a "counter" (usually the number of clicks on a button). You can use the method:

TOTP(uint8_t\* hmacKey, int keyLength, int timeStep);

passing as "timeStep" the number of clicks. What is difficult with HOTP is the syncronization as you don't have a common "clock". The RFC suggests a method to do that resyncronization but it must be implemented in your sketch...
